### ISSUE TITLE
aiothreads: More Informative timeout message

### ISSUE THREAD

**Issue by chrisjsewell** [muhrin/pytray#1]
From https://github.com/aiidateam/aiida-core/issues/4745, it might be helpful to allow for a more informative error message here:

https://github.com/muhrin/pytray/blob/371b22eb38d9ddfd4316bf139765acb1c02800de/pytray/aiothreads.py#L146-L155

along the lines of:

```python
def await_(self, awaitable: typing.Awaitable, exc_msg: str = ""):
    try:
	    return self.await_submit(awaitable).result(timeout=self.task_timeout)
    except TimeoutError:
	    raise TimeoutError(f"{exc_msg} after {self.task_timeout} seconds")
```

**Comment by muhrin** [comment]
Thanks Chris!  This has been added in #3f225bea803188fee7d8ba0a8dcb78cc0ef52a3b.
