### ISSUE TITLE
How to use for kivy

### ISSUE THREAD

**Issue by watchakorn-18k** [muhrin/pytray#3]
Please guide me

**Comment by muhrin** [comment]
Hi!  Thanks for writing.

I'm not sure I understand your request.  If you'd like to know how to use kiwiPy then you might find the documentation helpful:

https://kiwipy.readthedocs.io/en/latest/

As for the relationship between pytray and kiwiPy.  KiwiPy uses pytray as a library as it relies on some of the functionality from here.  For users of kiwiPy there is no need to even be aware of the existence of pytray as it is just used internally.

**Comment by watchakorn-18k** [comment]
thank you I found a way
